name: trab_front
description: "A new Flutter project."
publish_to: "none"

version: 1.0.2+3

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.4.9
  flutter_screenutil: ^5.9.0
  http: ^1.1.2
  permission_handler: ^11.1.0
  flutter_native_splash: ^2.3.9
  riverpod_annotation: ^2.3.3
  flutter_launcher_icons: ^0.13.1
  google_maps_flutter: ^2.5.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  kakao_flutter_sdk_user: ^1.8.0
  equatable: ^2.0.5
  dio: ^5.4.0
  dio_cache_interceptor: ^3.5.0
  dio_cache_interceptor_hive_store: ^3.2.2
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  path_provider: ^2.1.1
  flutter_secure_storage: ^9.0.0
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^5.0.0
  cached_network_image: ^3.3.1
  location: ^5.0.3
  flutter_svg: ^2.0.9
  image_picker: ^1.0.7
  adaptive_dialog: ^2.0.0
  geolocator: ^10.1.0
  animated_text_kit: ^4.2.2
  gif: ^2.3.0
  url_launcher: ^6.2.4
  flutter_dotenv: ^5.1.0

flutter_launcher_icons:
  image_path_android: "assets/images/trab_icon.png"
  image_path_ios: "assets/images/trab_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/trab_icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  background_color_ios: "#000000"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  riverpod_generator: ^2.3.9
  build_runner: ^2.4.6
  riverpod_lint: ^2.3.7
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/.
    - assets/svgs/.
    - assets/gifs/.
    - .env
  fonts:
    - family: Pretendard
      fonts:
        - asset: assets/fonts/Pretendard-Regular.ttf
          weight: 400
        - asset: assets/fonts/Pretendard-Medium.ttf
          weight: 500
        - asset: assets/fonts/Pretendard-Bold.ttf
          weight: 700
